### ISSUE TITLE
The Example doesn`t start

### ISSUE THREAD

**Issue by d69petkov** [brcolow/candlefx#2]
Hello Mike, thank you very much for sharing this code! Your solution using Canvas seems to be very interesting! Id like to test it, but I was unable to start the Example. The project build was successful, but when I try to RUN the Example module, I get the following error. Any idea where to dig? Im very beginner in Java and any help is appreciated!

Exception in Application start method
[main] ERROR com.brcolow.candlefx.example.CandleStickChartExample - [Thread[main,5,main]]: 
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalAccessError: superclass access check failed: class com.sun.javafx.scene.control.ControlHelper (in unnamed module @0x59c8777d) cannot access class com.sun.javafx.scene.layout.RegionHelper (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.layout to unnamed module @0x59c8777d
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at javafx.scene.control.Control.<clinit>(Control.java:86)
	at com.brcolow.candlefx.CandleStickChartToolbar.<init>(CandleStickChartToolbar.java:72)
	at com.brcolow.candlefx.CandleStickChartContainer.<init>(CandleStickChartContainer.java:46)
	at com.brcolow.candlefx.example.CandleStickChartExample.start(CandleStickChartExample.java:69)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	... 1 more

**Comment by brcolow** [comment]
Hmm that's very strange. What version of JavaFX are you using? It seems to be a JavaFX error.

**Comment by d69petkov** [comment]
Hi Mike, thanks for your response! Im on vacation now, but in September Il start seriously to learn the code. What I remember is that I just downloaded the .zip from GitHub and then opened the project with IntelliJ selecting the .pom file. I saw it requires JavaVersion 12, so I selected it in the project settings. It downloads itself JavaFX 14 according to the .pom and the libraries were there. The IntelliJ was complaining there is a duplicate module-info.java file, so I disable it and the build was successful. But I was unable to run it, so I tried different versions of Java with no success.
Anyway, thanks for sharing this one more time! Just close the issue anytime, for sure I`ll start it, but lamers like me need more time to realize where the problem is.

**Comment by brcolow** [comment]
No problem at all. I feel like it's a mismatch between JavaFX versions being included by IntelliJ and the source in your project. I highly recommend using a build tool such as Maven or Gradle and using them to build your project. This will manage the dependency complications for you.

**Comment by brcolow** [comment]
Going to close for now.
